apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-test-system
  title: Megan's Test System
  description: Verifying Backstage behavior for a test system
  annotations:
    newrelic.com/dashboard-guid: MjI1NTYyNnxWSVp8REFTSEJPQVJEfGRhOjY5OTE1MQ
spec:
  type: kube-service
  system: megan-backstage-test-system
  owner: my-test-group
  lifecycle: production

